### ISSUE TITLE
[Bug] v7.1.0 Browserlist warning in dev environment

### ISSUE THREAD

**Issue by kirklikecaptain** [react-static/react-static#1220]
After updating to react-static v7.1.0, the warning below is displayed in the terminal when the dev server is starting. It doesn't appear to cause any issues so far, but it's worth mentioning.

```
[✓] Templates Built
Bundling Application...
Fetching Site Data...
[✓] Site Data Downloaded (0.1s)

  Replace Autoprefixer browsers option to Browserslist config.
  Use browserslist key in package.json or .browserslistrc file.

  Using browsers option cause some error. Browserslist config
  can be used for Babel, Autoprefixer, postcss-normalize and other tools.

  If you really need to use option, rename it to overrideBrowserslist.

  Learn more at:
  https://github.com/browserslist/browserslist#readme
  https://twitter.com/browserslist



  Replace Autoprefixer browsers option to Browserslist config.
  Use browserslist key in package.json or .browserslistrc file.

  Using browsers option cause some error. Browserslist config
  can be used for Babel, Autoprefixer, postcss-normalize and other tools.

  If you really need to use option, rename it to overrideBrowserslist.

  Learn more at:
  https://github.com/browserslist/browserslist#readme
  https://twitter.com/browserslist



  Replace Autoprefixer browsers option to Browserslist config.
  Use browserslist key in package.json or .browserslistrc file.

  Using browsers option cause some error. Browserslist config
  can be used for Babel, Autoprefixer, postcss-normalize and other tools.

  If you really need to use option, rename it to overrideBrowserslist.

  Learn more at:
  https://github.com/browserslist/browserslist#readme
  https://twitter.com/browserslist


[✓] Application Bundled (20.5s)
```

**Comment by niboc** [comment]
How is it fixed?

**Comment by theWebalyst** [comment]
I just installed RS v7.1.0 and if I make a new 'basic' project, sometimes the dev server works, but then I run it again and it fails. Sometimes it fails right away and I don't see why. 

When it fails I get the warning as described in the OP, but in my case the website is broken. I see the page display for a moment and then a black screen with the following:

```
An internal error occured!

RoutesInner@http://localhost:3000/main.js:53224:13
renderWithHooks@http://localhost:3000/main.js:38775:22
mountIndeterminateComponent@http://localhost:3000/main.js:40931:17
beginWork@http://localhost:3000/main.js:41566:20
performUnitOfWork@http://localhost:3000/main.js:45610:16
workLoop@http://localhost:3000/main.js:45651:28
renderRoot@http://localhost:3000/main.js:45731:11
performWorkOnRoot@http://localhost:3000/main.js:46688:11
performWork@http://localhost:3000/main.js:46598:11
performSyncWork@http://localhost:3000/main.js:46572:7
requestWork@http://localhost:3000/main.js:46427:9
retryTimedOutBoundary@http://localhost:3000/main.js:46107:11
wrapped@http://localhost:3000/main.js:59055:38       
```

I'm using Ubuntu 18.10, yarn v1.15.2 and `yarn global add react-static`.

Is there a v7 version that is known to work which I can use in the mean time?

**Comment by theWebalyst** [comment]
Ahah. Possible workaround.

It seems that running the package.json scripts (e.g. `npm run start`) rather than running `react-static` from the command line avoids the messages in the OP and the failure I reported immediately above. Same with `npm run build` / `npm run serve -p 3000`. All seem to work fine when run via `npm`.

**Comment by SleeplessByte** [comment]
Fixed via https://github.com/react-static/react-static/pull/1283/commits/7c244e45dbdbf8dd12cc4c09ad412253db869cf2

**Comment by karlmacklin** [comment]
I'm on version 7.2.2 of react-static. Latest version of browserlist (4.7.2).

Still getting this error, tons of them, when running react-static start.

So, I've tried adding to .browserslist:
```
# Browsers that we support

last 1 version
> 1%
maintained node versions
not dead
```

And package.json:

```
"browserslist": [
    "last 1 version",
    "> 1%",
    "maintained node versions",
    "not dead"
  ]
```

Tried all combos of them (only rc file, only package.json, both).
No go.

Should I raise a new bug report?

**Comment by karlmacklin** [comment]
If anyone else still is having this problem, double check the sass plugin is also updated, not only react-static.
