### ISSUE TITLE
[Bug] react-static build hangs forever on all templates

### ISSUE THREAD

**Issue by LPGhatguy** [react-static/react-static#1298]
Building even the 'empty' template does not ever finish on my machine. This is frustrating because it feels like an important piece of functionality that prevents adoption of react-static.

### Environment
```
  System:
    OS: Windows 10
    CPU: (16) x64 AMD Ryzen 7 1700X Eight-Core Processor
    Memory: 9.09 GB / 15.95 GB
  Binaries:
    Node: 10.16.3 - C:\Program Files\nodejs\node.EXE
    npm: 6.9.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 44.17763.1.0
    Internet Explorer: 11.0.17763.592
  npmPackages:
    react: ^16.9.0 => 16.9.0
    react-dom: ^16.9.0 => 16.9.0
    react-static: ^7.2.0 => 7.2.0
    react-static-plugin-reach-router: ^7.2.0 => 7.2.0
    react-static-plugin-sitemap: ^7.2.0 => 7.2.0
    react-static-plugin-source-filesystem: ^7.2.0 => 7.2.0
```

### Steps to Reproduce the problem
1. `react-static create`
2. Pick "empty"
3. `cd my-static-site`
4. `npm run build`

### Expected Behavior
The site is built into the `dist` directory.

### Observed Behavior
The process hangs forever on the "Bundling App..." step:

```
lucien /c/projects/my-static-site
$ npm run build

> react-static-example-blank@ build C:\projects\my-static-site
> react-static build

Bundling application for Production...

Cleaning dist...
[✓] Dist cleaned (0.2s)
Cleaning artifacts...
[✓] Artifacts cleaned
Building Routes...
Importing routes from directory...
[✓] Routes Built (0.1s)
Building Templates...
[✓] Templates Built
Copying public directory...
[✓] Public directory copied
Bundling App...
```

I thought it might be my shell or terminal emulator, so I tried the same command on `cmd.exe`, Git Bash with ConHost, and Git Bash with Alacritty (my default setup). No dice.

**Comment by SleeplessByte** [comment]
This is marked in the release notes: https://github.com/react-static/react-static/releases/tag/v7.2.0

> 🚧 There is a known issue where on Windows, sometimes, build or start will hang. In these cases, try running with --debug or --dev. This will be resolved in a later version.

**Comment by LPGhatguy** [comment]
Is there another issue tracking this bug? I noticed that it was mentioned in the big 7.2.0 PR as a "note to self", I want to make sure that this doesn't get lost and left unresolved.

**Comment by SleeplessByte** [comment]
I'm on Windows, so is half the company, so we _actively_ have this issue _every day 😅 _. Don't worry, it won't be forgotten!

**Comment by SleeplessByte** [comment]
Should be fixed in 7.2.3!

**Comment by dev-rsilver** [comment]
Basic template is still hanging on "Bundling App..." for me on 7.2.3. Windows 10, tried with both yarn and npm.

**Comment by Herohtar** [comment]
@SleeplessByte Still hanging for me in 7.2.3 on Windows 10 as well.

**Comment by SleeplessByte** [comment]
Ok. We've fixed it on RS 8. For now I recommend to downgrade to 7.1.0 for the time being!

**Comment by ivan-rakic** [comment]
Yea, 7.1.0 isn't working either....
